name: University of Wisconsin Oshkosh
baseurl: http://www.uwosh.edu/beta
exclude:
  - .gitignore
  - README.md
  - Gruntfile.js
  - package.json
  - bower.json
  - Gemfile
  - Gemfile.lock
facebook: https://www.facebook.com/uwoshkosh
twitter: https://twitter.com/uwoshkosh
youtube: http://www.youtube.com/uwosh
google-plus: https://plus.google.com/u/1/+uwoshkosh/posts
pinterest: http://www.pinterest.com/uwoshkosh/
flickr: http://www.flickr.com/photos/uwoshkosh/sets/
